# Generated by Django 3.1.1 on 2022-05-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0004_auto_20220502_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='AssignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.teams'),
        ),
    ]
