# Generated by Django 3.1.1 on 2022-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0005_auto_20220503_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='AssignedTime',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
